M48
; DRILL file {KiCad (6.0.1-0)} date Tuesday, December 27, 2022 at 01:34:04 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-27T13:34:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X2.0299Y-5.1307
X2.2575Y-5.1307
T2
X3.5335Y-5.0925
X3.7264Y-5.0925
T3
X4.5059Y-4.9606
X4.5059Y-5.2362
T4
X1.9764Y-3.3563
X2.4685Y-5.2264
X4.1417Y-5.2264
X4.6339Y-3.3563
T0
M30
